"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse, parse_qs
from dotenv import load_dotenv


def _split_env_list(value):
    return [item.strip() for item in value.split(',') if item and item.strip()]


def _normalize_host(host):
    host = host.strip()
    if not host:
        return ''
    if '://' in host:
        host = urlparse(host).netloc
    host = host.split('/')[0]
    host = host.split(':')[0]
    return host


def _normalize_origin(origin):
    origin = origin.strip()
    if not origin:
        return ''
    if origin.startswith('http://') or origin.startswith('https://'):
        return origin.rstrip('/')
    return f'https://{_normalize_host(origin)}'

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Configure ALLOWED_HOSTS for local + Render hostnames
allowed_hosts_env = _split_env_list(os.getenv('ALLOWED_HOSTS', ''))
render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS.extend([_normalize_host(host) for host in allowed_hosts_env if _normalize_host(host)])
if render_hostname:
    ALLOWED_HOSTS.append(_normalize_host(render_hostname))

# Keep order stable and unique
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'base.apps.BaseConfig', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', '').strip()

if DATABASE_URL:
    parsed = urlparse(DATABASE_URL)
    query = parse_qs(parsed.query)
    sslmode = os.getenv('DB_SSLMODE', query.get('sslmode', ['require'])[0])

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/'),
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': str(parsed.port or 5432),
            'OPTIONS': {
                'client_encoding': 'UTF8',
                'sslmode': sslmode,
            },
        }
    }
else:
    db_host = os.getenv('DB_HOST', 'localhost')
    db_sslmode = os.getenv('DB_SSLMODE', 'require' if db_host not in ['localhost', '127.0.0.1'] else 'disable')

    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
            'NAME': os.getenv('DB_NAME', 'postgres'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': db_host,
            'PORT': os.getenv('DB_PORT', '5432'),
            'OPTIONS': {
                'client_encoding': 'UTF8',
                'sslmode': db_sslmode,
            },
        }
    }




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Trust Render proxy for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS / CSRF configuration
cors_allowed_origins = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://sneakr-lab-tau.vercel.com',
]

frontend_url = os.getenv('FRONTEND_URL', '').strip()
if frontend_url:
    normalized_frontend = _normalize_origin(frontend_url)
    if normalized_frontend:
        cors_allowed_origins.append(normalized_frontend)

extra_cors = _split_env_list(os.getenv('CORS_ALLOWED_ORIGINS', ''))
cors_allowed_origins.extend([_normalize_origin(origin) for origin in extra_cors if _normalize_origin(origin)])

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(cors_allowed_origins))

csrf_trusted = []
if frontend_url:
    normalized_frontend = _normalize_origin(frontend_url)
    if normalized_frontend:
        csrf_trusted.append(normalized_frontend)
csrf_trusted.extend([_normalize_origin(origin) for origin in _split_env_list(os.getenv('CSRF_TRUSTED_ORIGINS', '')) if _normalize_origin(origin)])
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(csrf_trusted))

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}
